name: Run nightly tests

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests on IDA nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Install IDA nightly
        run: |
          echo "Installing hcli..."
          uv tool install ida-hcli==0.15.0
          echo "Downloading and installing IDA nightly..."
          mkdir -p /opt/ida/
          hcli ida install -d ida-pro:nightly -l ${{ secrets.IDA_LICENSE_ID }} -i /opt/ida/
          echo "Done!"
        env:
          HCLI_API_KEY: ${{ secrets.HCLI_API_KEY }}

      - name: Sync dependencies
        run: uv sync --extra dev

      - name: Install idapro
        run: uv pip install idapro

      - name: Run tests and generate coverage
        run: uv run coverage run --source=ida_domain -m pytest -v --junitxml=test-results.xml
        env:
          IDADIR: /opt/ida/

      - name: Generate coverage reports
        run: |
          uv run coverage report --include="ida_domain/*"
          uv run coverage xml --include="ida_domain/*"
          uv run coverage html --include="ida_domain/*"

      - name: Upload test results and coverage
        uses: actions/upload-artifact@v7
        if: ${{ always() }}
        with:
          name: nightly-test-results-and-coverage
          path: |
            test-results.xml
            coverage.xml
            htmlcov/
          retention-days: 30
